kind: Secret
apiVersion: v1
metadata:
  name: tempconverter
  namespace: posh
  uid: 072435bb-ee0b-4852-b801-61956327a2b2
  resourceVersion: '16465244'
  creationTimestamp: '2023-06-02T19:42:59Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2023-06-02T19:42:59Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:COLLEGE': {}
          'f:DB_HOST': {}
          'f:DB_NAME': {}
          'f:DB_PASS': {}
          'f:DB_USER': {}
          'f:STUDENT': {}
        'f:type': {}
data:
  COLLEGE: QWxnZWJyYQ==
  DB_HOST: bXlzcWw=
  DB_NAME: dGVtcGNvbnZlcnRlcg==
  DB_PASS: aXZhbmExMjM=
  DB_USER: aXZhbmE=
  STUDENT: SXZhbmEgQmlsaWM=
type: Opaque
