kind: Secret
apiVersion: v1
metadata:
  name: mysql
  namespace: posh
  uid: d3c1137e-863b-4e37-878a-2d67e9860d0e
  resourceVersion: '16445635'
  creationTimestamp: '2023-06-02T18:54:37Z'
  labels:
    template: mysql-persistent-template
    template.openshift.io/template-instance-owner: ed71538f-a1fb-487e-9e6c-8e39d21c0ed4
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  managedFields:
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-06-02T18:54:37Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:database-name': {}
          'f:database-password': {}
          'f:database-root-password': {}
          'f:database-user': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:template.openshift.io/expose-database_name': {}
            'f:template.openshift.io/expose-password': {}
            'f:template.openshift.io/expose-root_password': {}
            'f:template.openshift.io/expose-username': {}
          'f:labels':
            .: {}
            'f:template': {}
            'f:template.openshift.io/template-instance-owner': {}
        'f:type': {}
data:
  database-name: dGVtcGNvbnZlcnRlcg==
  database-password: aXZhbmExMjM=
  database-root-password: cjAwdHBhNTU=
  database-user: aXZhbmE=
type: Opaque
